---
- name: be sure epel repository is installed
  yum: name=https://dl.fedoraproject.org/pub/epel/6Server/x86_64/epel-release-6-8.noarch.rpm
  notify:
    - import epel key
  tags: epel

- name: disable epel repository
  ini_file: dest=/etc/yum.repos.d/epel.repo section="epel" option="enabled" value="0"
  tags: epel
