---
- name: be sure epel repository is installed
  yum: name=epel-release state=installed
  notify:
    - import epel key
  tags: epel

- name: disable epel repository
  ini_file: dest=/etc/yum.repos.d/epel.repo section="epel" option="enabled" value="0"
  tags: epel
