---
- include: timezone.yml
- include: locale.yml
- include: rpmforge.yml
- include: epel.yml
- include: remi.yml
- include: packages.yml
- include: yum-cron.yml
- include: sshd.yml
- include: chrony.yml
