---
- name: yum update
  yum: name=* state=latest

- name: be sure system packages are installed
  yum: name={{ item }} state=installed
  with_items: sys_packages
  tags: packages

- name: be sure remi system packages are installed
  yum: name={{ item }} state=installed enablerepo=remi
  with_items: sys_remi_packages
  tags: packages