- name: configure timezone
  template: src=timezone.tpl dest=/etc/timezone
  tags: timezone

- name: more configure timezone
  file: src=/usr/share/zoneinfo/{{timezone}} dest=/etc/localtime state=link force=yes backup=yes
  tags: timezone
