---
- name: be sure yum-cron is installed
  yum: name=yum-cron state=installed
  tags: yum-cron

- name: be sure yum-cron is running and enabled
  service: name=yum-cron state=running enabled=yes
  tags: yum-cron

- name: configure yum-cron
  lineinfile: >
    dest=/etc/yum/yum-cron.conf
    state=present
    owner=root
    group=root
    mode=0644
    backup=yes
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
  with_items:
    - regexp: '^apply_updates ='
      line: 'apply_updates = yes'
    - regexp: '^update_cmd ='
      line: 'update_cmd = security'
  notify: restart yum-cron
  tags: yum-cron
