---
- hosts: all
  sudo: true
  vars:
    timezone: Asia/Tokyo
  vars_files:
    - vars/packages.yml
    - vars/postgresql.yml
  roles:
    - init
    - apache
    - php
    - composer
    - postgresql
