---
- name: be sure pgdg repository is installed
  yum: name=http://yum.postgresql.org/9.4/redhat/rhel-6-x86_64/pgdg-centos94-9.4-1.noarch.rpm
  notify:
    - import pgdg key
  tags: postgresql

- name: be sure postgresql is installed
  yum: pkg={{item}} state=latest
  with_items:
    - postgresql94-server
    - postgresql94-contrib
    - postgresql94
    - python-psycopg2
  tags: postgresql

- name: check whether postgresql.conf exists or not
  shell: "[ -f /var/lib/pgsql/9.4/data/postgresql.conf ] && echo 'Found' || echo ''"
  register: postgresql_conf_exists
  tags: postgresql

- name: initiate database
  shell: /usr/pgsql-9.4/bin/postgresql94-setup initdb
  when: (not postgresql_conf_exists.stdout)
  tags: postgresql

- name: be sure postgresql is running and enabled
  service: name=postgresql-9.4 state=started enabled=yes
  tags: postgresql

- name: ensure PostgreSQL is listening on all hosts
  lineinfile: dest=/var/lib/pgsql/9.4/data/postgresql.conf
              backup=yes
              regexp='^#?listen_addresses\s*='
              line="listen_addresses = '*'"
              state=present
  tags: postgresql

- name: ensure access from localhost
  lineinfile: >
    dest=/var/lib/pgsql/9.4/data/pg_hba.conf
    backup=yes
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
  with_items:
    - regexp: 'local\s+all\s+all\s+peer'
      line: 'local all all trust'
    - regexp: 'host\s+all\s+all\s+127.0.0.1/32\s+ident'
      line: 'host all all 127.0.0.1/32 md5'
  tags: postgresql

- name: be sure postgresql is restarted
  service: name=postgresql-9.4 state=restarted
  tags: postgresql

- name: create db
  postgresql_db: name={{ dbname }}
  tags: postgresql

- name: add user
  postgresql_user: db={{ dbname }} name={{ dbuser }} password={{ dbpass }}
  tags: postgresql
